### ISSUE TITLE
Missing parameter: `headers`

### ISSUE THREAD

**Issue by rakibulalam** [hoangnguyen1247/oauth2-server-ts#11]
i am trying to implement oauth2 using graphQL. 

```
@Query(()=>String)
  token(@GetContext() {req,res}) {
   console.log(req,res)
    return this.authServerService.getToken(req, res)
  }
```
The following error has appeared 

Missing parameter: `headers`

**Comment by rakibulalam** [comment]
Get it. It was the nest context issues.

**Comment by hoangnguyen1247** [comment]
Hi @rakibulalam this package i port from node-oauth2-server
if you are using with Express and Typescript, you can use this package https://github.com/hoangnguyen1247/oauth2-server-ts-express as a wrapper
i don't setup a release flow to maintain this package yet, but if you need some support i can help
